### ISSUE TITLE
run.bat not updated in netsimulator-1.1-SNAPSHOT-bin.zip

### ISSUE THREAD

**Issue by MaximilianWithTheRose** [checkpoint20/net-simulator#7]
In [release](https://github.com/checkpoint20/net-simulator/releases) archive `netsimulator-1.1-SNAPSHOT-bin.zip` in `run.bat` there's a wrong line. [Commit](https://github.com/checkpoint20/net-simulator/pull/5/commits/7daddbd0f1d4ffff3a5e04db42d9c1ce2aa57864) isn't implemented.

run.bat in said archive:
`java -Djava.util.logging.config.file=cfg\logging.properties -jar org.netsimulator.Netsimulator`

corrected run.bat:
`java -Djava.util.logging.config.file=cfg\logging.properties -jar netsimulator-1.1-SNAPSHOT.jar`

**Comment by checkpoint20** [comment]
Fixed in v1.1.0
